# Generated by Django 5.1.5 on 2025-10-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=20),
        ),
    ]
